on:
  push:
    branches: [ dev ]
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 18.18.2 to Build
      uses: actions/setup-node@v2
      with:
        node-version: 18.18.2
    - run: npm install
    - run: CI=false npm start > /home/ubuntu/apps/assetank/assetank-logs.txt &
    - name: ssh deploy on aws lightsail
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_KEY }}
        REMOTE_HOST: ${{ secrets.DEPLOY_HOST }}
        REMOTE_USER: ${{ secrets.DEPLOY_USER }}
        REMOTE_PORT: ${{ secrets.DEPLOY_PORT }}
        SOURCE: "build/"
        TARGET: ${{ secrets.DEPLOY_TARGET }}
