name: Deploy to Lightsail

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - name: Create config.env file from config.env
        run: |
          echo "${{ secrets.CONFIG_ENV_CONTENT }}" > config.env
      - name: Install dependencies
        run: npm ci
      - name: Deploy to Lightsail
        env:
          LIGHTSAIL_IP: ${{ secrets.DEPLOY_HOST }}
          LIGHTSAIL_SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i $DEPLOY_KEY ubuntu@$DEPLOY_HOST <<EOF
          cd /home/ubuntu/apps/assetank/stg/pcs-be
          git pull
          npm install
          npm start
          EOF
