name: Deploy to Lightsail

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - name: Create config.env file from config.env
        run: |
          echo "${{ secrets.CONFIG_ENV_CONTENT }}" > config.env
      - name: Install dependencies
        run: npm ci
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.DEPLOY_PORT }}
          script: |
            cd /home/ubuntu/apps/assetank/stg/pcs-be
            git pull
            npm install
            npm start
            EOF
