on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.18.2 to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - name: Create config.env file from config.env
        run: |
          echo "${{ secrets.CONFIG_ENV_CONTENT }}" > config.env
      - name: Deploy to Lightsail
        run: |
          ssh -i ${{ secrets.DEPLOY_KEY }} ubuntu@${{ secrets.DEPLOY_HOST }} 'cd /home/ubuntu/apps/assetank/stg/pcs-be && mkdir test123 && git pull && npm install && npm start'
