on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 18.18.2 to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - run: npm install
      - name: Create config.env file from config.env
        run: |
          echo "${{ secrets.CONFIG_ENV_CONTENT }}" > config.env
      - run: CI=false npm start &
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd /home/ubuntu/apps/assetank/stg/pcs-be
            mkdir testtest
            source ~/.nvm/nvm.sh
            npm start > /home/ubuntu/apps/assetank/assetank-logs.txt &
            echo "Server started"
