on:
  push:
    branches: [dev]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.18.2 to Build
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
      - run: npm install
      - name: Create config.env file from config.env
        run: |
          echo "${{ secrets.CONFIG_ENV_CONTENT }}" > config.env
      - run: CI=false npm start &
      - name: Deploy to Lightsail
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          port: ${{ secrets.DEPLOY_PORT }}
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ${{ secrets.DEPLOY_TARGET }}
            source ~/.nvm/nvm.sh
            git pull origin dev
            npm install
            sudo kill -9 $(sudo lsof -t -i:4000)
            nohup npm start > ${{ secrets.DEPLOY_LOGS }} 2>&1 &
            echo "Server started"
